// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using State.Infrastructure.Context;

#nullable disable

namespace State.Infrastructure.Migrations
{
    [DbContext(typeof(StateDbContext))]
    [Migration("20211205180444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("State.Api.Entities.StateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acre",
                            Population = 906876
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alagoas",
                            Population = 3365351
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amapá",
                            Population = 877613
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amazonas",
                            Population = 4269995
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bahia",
                            Population = 14985284
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ceará",
                            Population = 9240580
                        },
                        new
                        {
                            Id = 7,
                            Name = "Distrito Federal",
                            Population = 3094325
                        },
                        new
                        {
                            Id = 8,
                            Name = "Espírito Santo",
                            Population = 4108508
                        },
                        new
                        {
                            Id = 9,
                            Name = "Goiás",
                            Population = 7206589
                        },
                        new
                        {
                            Id = 10,
                            Name = "Maranhão",
                            Population = 7153262
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mato Grosso",
                            Population = 3567234
                        },
                        new
                        {
                            Id = 12,
                            Name = "Mato Grosso do Sul",
                            Population = 2839188
                        },
                        new
                        {
                            Id = 13,
                            Name = "Minas Gerais",
                            Population = 21411923
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pará",
                            Population = 8777124
                        },
                        new
                        {
                            Id = 15,
                            Name = "Paraíba",
                            Population = 4059905
                        },
                        new
                        {
                            Id = 16,
                            Name = "Paraná",
                            Population = 11597484
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pernambuco",
                            Population = 9674793
                        },
                        new
                        {
                            Id = 18,
                            Name = "Piauí",
                            Population = 3289290
                        },
                        new
                        {
                            Id = 19,
                            Name = "Rio de Janeiro",
                            Population = 17463349
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rio Grande do Norte",
                            Population = 3560903
                        },
                        new
                        {
                            Id = 21,
                            Name = "Rio Grande do Sul",
                            Population = 11466630
                        },
                        new
                        {
                            Id = 22,
                            Name = "Rondônia",
                            Population = 1815278
                        },
                        new
                        {
                            Id = 23,
                            Name = "Roraima",
                            Population = 652713
                        },
                        new
                        {
                            Id = 24,
                            Name = "Santa Catarina",
                            Population = 7338443
                        },
                        new
                        {
                            Id = 25,
                            Name = "São Paulo",
                            Population = 41262199
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sergipe",
                            Population = 2338474
                        },
                        new
                        {
                            Id = 27,
                            Name = "Tocantins",
                            Population = 1607363
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
