// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using State.Api.Repositories;

#nullable disable

namespace State.Api.Migrations
{
    [DbContext(typeof(StateDbContext))]
    [Migration("20211202014926_SeedAllStateTable")]
    partial class SeedAllStateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("State.Api.Entities.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("State.Api.Entities.StateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acre"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amapá"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pará"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = 25,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Tocantins"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
